### ISSUE TITLE
Motion Sensor

### ISSUE THREAD

**Issue by marbaugh** [automaton82/MQTT-concord4#2]
In my setup, Zone 2 is a motion sensor so I set it up using:
  - platform: mqtt
    device_class: motion
    name: "Zone2"
    state_topic: "concord/zone/2"
    payload_on: "active"
    payload_off: "inactive"

The MQTT broker is sending zone 2 as open or closed though it is a motion sensor.  Can you fix this to send inactive/active?

**Comment by automaton82** [comment]
The original code this is based on has always sent ```open``` and ```closed``` as the values for any sensor, including smoke alarms, glass brake etc.

However you could definitely modify it to send other values for other sensors or even zones specifically if you wanted. I suggest you fork it and look where ```updateStateOnMQTT``` is called to modify it there.

**Comment by marbaugh** [comment]
I just found where I can set silent=True.

 def ArmDisarm(self, action='stay', arm_silent = True, bypasszone='',partition_num=1):
        log.debug("Menu item: Arm/Disarm: %s" % str(action))

**Comment by marbaugh** [comment]
Got it, thanks so much!  Everything is working great and so much easier now without need to rely on SmartThings.

**Comment by automaton82** [comment]
Great!
